name: sync up to sourcecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "test url : ${{ secrets.TEST_REPOSITORY_URL }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Sync up to SourceCommit
        uses: es5h/sync-up-to-sourcecommit-action@test10
        with:
          repository_url: 'ssh://devtools.ncloud.com/3045698/Dairy-Dapr-Practice.git'
          ssh_private_key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          ssh_key: ${{ secrets.TEST_SSH_KEY }}
          
