name: sync up to sourcecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync up to SourceCommit
        uses: es5h/sync-up-to-sourcecommit-action@test18
        with:
          repository_url: ${{ secrets.TEST_REPOSITORY_URL }}
          ssh_private_key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.TEST_SSH_PUBLIC_KEY }}
          ssh_key: ${{ secrets.TEST_SSH_KEY }}
          
